# Generated by Django 3.1.4 on 2020-12-31 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jumga.extras


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('phone_number', jumga.extras.CharNullField(blank=True, default=None, max_length=18, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider',
            },
        ),
    ]
