# Generated by Django 3.1.4 on 2021-01-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rider',
        ),
    ]
