# Generated by Django 3.1.4 on 2021-01-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_remove_order_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sub_domain',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
