# Generated by Django 3.1.4 on 2020-12-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20201231_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
