# Generated by Django 3.1.4 on 2021-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_payment_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='beneficary',
            new_name='beneficiary',
        ),
    ]
