# Generated by Django 3.1.4 on 2020-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_auto_20201231_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sub_domain',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
