# Generated by Django 3.1.4 on 2020-12-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rider'),
        ('merchant', '0005_auto_20201231_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.rider'),
        ),
    ]
