# Generated by Django 3.1.4 on 2021-01-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_auto_20210106_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchant.shop'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=5),
        ),
    ]
