# Generated by Django 3.1.4 on 2021-01-08 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_transaction_tx_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tx_ref',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_ref_from_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.payment'),
        ),
    ]
