# Generated by Django 3.1.4 on 2021-01-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_auto_20210108_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='narration',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='transaction',
            name='narration',
            field=models.CharField(default='', max_length=256),
        ),
    ]
