# Generated by Django 3.1.4 on 2021-01-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_auto_20210110_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
    ]
