# Generated by Django 3.1.4 on 2021-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_remove_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_id',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
