# Generated by Django 3.1.4 on 2021-01-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0012_auto_20210111_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_instruction',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
